export const GOOGLEFILE_SELECTED = 'GOOGLEFILE_SELECTED';
export const GOOGLEFILE_CLEAN = 'GOOGLEFILE_CLEAN';
export const GOOGLEFILE_SAVED = 'GOOGLEFILE_SAVED';
export const GOOGLEFILE_SAVED_CLEAN = 'GOOGLEFILE_SAVED_CLEAN';

export const BOOKINGFILE_SELECTED = 'BOOKINGFILE_SELECTED';
export const BOOKINGFILE_CLEAN = 'BOOKINGFILE_CLEAN';
export const BOOKINGFILE_SAVED = 'BOOKINGFILE_SAVED';
export const BOOKINGFILE_SAVED_CLEAN = 'BOOKINGFILE_SAVED_CLEAN';

export const TRIVAGOFILE_SELECTED = 'TRIVAGOFILE_SELECTED';
export const TRIVAGOFILE_CLEAN = 'TRIVAGOFILE_CLEAN';
export const TRIVAGOFILE_SAVED = 'TRIVAGOFILE_SAVED';
export const TRIVAGOFILE_SAVED_CLEAN = 'TRIVAGOFILE_SAVED_CLEAN';