export const GOOGLEFILE_SELECTED = 'GOOGLEFILE_SELECTED';
export const GOOGLEFILE_CLEAN = 'GOOGLEFILE_CLEAN';

export const BOOKINGFILE_SELECTED = 'BOOKINGFILE_SELECTED';
export const BOOKINGFILE_CLEAN = 'BOOKINGFILE_CLEAN';

export const EXPEDIAFILE_SELECTED = 'EXPEDIAFILE_SELECTED';
export const EXPEDIAFILE_CLEAN = 'EXPEDIAFILE_CLEAN';